# coding: utf-8

"""
    AVACloud API 1.30.0

    AVACloud API specification  # noqa: E501

    OpenAPI spec version: 1.30.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from avacloud_client_python.configuration import Configuration


class OenormPropertiesDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'origin_code': 'OenormOriginCodeDto',
        'opening_text_is_free_text': 'bool'
    }

    attribute_map = {
        'origin_code': 'originCode',
        'opening_text_is_free_text': 'openingTextIsFreeText'
    }

    def __init__(self, origin_code=None, opening_text_is_free_text=None, _configuration=None):  # noqa: E501
        """OenormPropertiesDto - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._origin_code = None
        self._opening_text_is_free_text = None
        self.discriminator = None

        self.origin_code = origin_code
        self.opening_text_is_free_text = opening_text_is_free_text

    @property
    def origin_code(self):
        """Gets the origin_code of this OenormPropertiesDto.  # noqa: E501

        This indicates where the content of this element originates, if set. It corresponds to 'herkunftskennzeichen' in ÖNorm  # noqa: E501

        :return: The origin_code of this OenormPropertiesDto.  # noqa: E501
        :rtype: OenormOriginCodeDto
        """
        return self._origin_code

    @origin_code.setter
    def origin_code(self, origin_code):
        """Sets the origin_code of this OenormPropertiesDto.

        This indicates where the content of this element originates, if set. It corresponds to 'herkunftskennzeichen' in ÖNorm  # noqa: E501

        :param origin_code: The origin_code of this OenormPropertiesDto.  # noqa: E501
        :type: OenormOriginCodeDto
        """
        if self._configuration.client_side_validation and origin_code is None:
            raise ValueError("Invalid value for `origin_code`, must not be `None`")  # noqa: E501

        self._origin_code = origin_code

    @property
    def opening_text_is_free_text(self):
        """Gets the opening_text_is_free_text of this OenormPropertiesDto.  # noqa: E501

        This marks if the opening texts within this element are considered free text. It corresponds to 'vorbemerkungskennzeichen' in ÖNorm.  # noqa: E501

        :return: The opening_text_is_free_text of this OenormPropertiesDto.  # noqa: E501
        :rtype: bool
        """
        return self._opening_text_is_free_text

    @opening_text_is_free_text.setter
    def opening_text_is_free_text(self, opening_text_is_free_text):
        """Sets the opening_text_is_free_text of this OenormPropertiesDto.

        This marks if the opening texts within this element are considered free text. It corresponds to 'vorbemerkungskennzeichen' in ÖNorm.  # noqa: E501

        :param opening_text_is_free_text: The opening_text_is_free_text of this OenormPropertiesDto.  # noqa: E501
        :type: bool
        """
        if self._configuration.client_side_validation and opening_text_is_free_text is None:
            raise ValueError("Invalid value for `opening_text_is_free_text`, must not be `None`")  # noqa: E501

        self._opening_text_is_free_text = opening_text_is_free_text

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list([x.to_dict() if hasattr(x, "to_dict") else x for x in value])
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict([(item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item for item in list(value.items())])
            else:
                result[attr] = value
        if issubclass(OenormPropertiesDto, dict):
            for key, value in list(self.items()):
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OenormPropertiesDto):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, OenormPropertiesDto):
            return True

        return self.to_dict() != other.to_dict()

