# coding: utf-8

"""
    AVACloud API 1.52.1

    AVACloud API specification  # noqa: E501

    OpenAPI spec version: 1.52.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""




import unittest

import avacloud_client_python
from avacloud_client_python.models.destination_reb_type import DestinationRebType  # noqa: E501
from avacloud_client_python.rest import ApiException


class TestDestinationRebType(unittest.TestCase):
    """DestinationRebType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDestinationRebType(self):
        """Test DestinationRebType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = avacloud_client_python.models.destination_reb_type.DestinationRebType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
