# coding: utf-8

"""
    AVACloud API 1.41.0

    AVACloud API specification  # noqa: E501

    OpenAPI spec version: 1.41.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""




import unittest

import avacloud_client_python
from avacloud_client_python.api.datanorm_conversion_api import DatanormConversionApi  # noqa: E501
from avacloud_client_python.rest import ApiException


class TestDatanormConversionApi(unittest.TestCase):
    """DatanormConversionApi unit test stubs"""

    def setUp(self):
        self.api = avacloud_client_python.api.datanorm_conversion_api.DatanormConversionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_datanorm_conversion_convert_to_ava(self):
        """Test case for datanorm_conversion_convert_to_ava

        Converts Datanorm files to Dangl.AVA projects  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()

