# coding: utf-8

"""
    AVACloud API 1.52.1

    AVACloud API specification  # noqa: E501

    OpenAPI spec version: 1.52.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import avacloud_client_python
from avacloud_client_python.models.party_information_dto import PartyInformationDto  # noqa: E501
from avacloud_client_python.rest import ApiException


class TestPartyInformationDto(unittest.TestCase):
    """PartyInformationDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPartyInformationDto(self):
        """Test PartyInformationDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = avacloud_client_python.models.party_information_dto.PartyInformationDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
