# coding: utf-8

"""
    AVACloud API 1.27.4

    AVACloud API specification  # noqa: E501

    OpenAPI spec version: 1.27.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""




import unittest

import avacloud_client_python
from avacloud_client_python.models.destination_oenorm_type import DestinationOenormType  # noqa: E501
from avacloud_client_python.rest import ApiException


class TestDestinationOenormType(unittest.TestCase):
    """DestinationOenormType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDestinationOenormType(self):
        """Test DestinationOenormType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = avacloud_client_python.models.destination_oenorm_type.DestinationOenormType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()

