# coding: utf-8

"""
    AVACloud API 1.27.4

    AVACloud API specification  # noqa: E501

    OpenAPI spec version: 1.27.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import avacloud_client_python
from avacloud_client_python.models.gross_price_component_dto import GrossPriceComponentDto  # noqa: E501
from avacloud_client_python.rest import ApiException


class TestGrossPriceComponentDto(unittest.TestCase):
    """GrossPriceComponentDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGrossPriceComponentDto(self):
        """Test GrossPriceComponentDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = avacloud_client_python.models.gross_price_component_dto.GrossPriceComponentDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
