# coding: utf-8

"""
    AVACloud API 1.5.7

    AVACloud API specification  # noqa: E501

    OpenAPI spec version: 1.5.7
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import avacloud_client_python
from avacloud_client_python.models.warranty_duration_dto import WarrantyDurationDto  # noqa: E501
from avacloud_client_python.rest import ApiException


class TestWarrantyDurationDto(unittest.TestCase):
    """WarrantyDurationDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWarrantyDurationDto(self):
        """Test WarrantyDurationDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = avacloud_client_python.models.warranty_duration_dto.WarrantyDurationDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
