# coding: utf-8

"""
    AVACloud API 1.26.0

    AVACloud API specification  # noqa: E501

    OpenAPI spec version: 1.26.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import avacloud_client_python
from avacloud_client_python.models.oenorm_position_properties_dto import OenormPositionPropertiesDto  # noqa: E501
from avacloud_client_python.rest import ApiException


class TestOenormPositionPropertiesDto(unittest.TestCase):
    """OenormPositionPropertiesDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOenormPositionPropertiesDto(self):
        """Test OenormPositionPropertiesDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = avacloud_client_python.models.oenorm_position_properties_dto.OenormPositionPropertiesDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
