# coding: utf-8

"""
    AVACloud API 1.41.0

    AVACloud API specification  # noqa: E501

    OpenAPI spec version: 1.41.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import avacloud_client_python
from avacloud_client_python.models.execution_description_dto import ExecutionDescriptionDto  # noqa: E501
from avacloud_client_python.rest import ApiException


class TestExecutionDescriptionDto(unittest.TestCase):
    """ExecutionDescriptionDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExecutionDescriptionDto(self):
        """Test ExecutionDescriptionDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = avacloud_client_python.models.execution_description_dto.ExecutionDescriptionDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
