# coding: utf-8

"""
    AVACloud API 1.30.0

    AVACloud API specification  # noqa: E501

    OpenAPI spec version: 1.30.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""




import unittest

import avacloud_client_python
from avacloud_client_python.models.price_type_dto import PriceTypeDto  # noqa: E501
from avacloud_client_python.rest import ApiException


class TestPriceTypeDto(unittest.TestCase):
    """PriceTypeDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPriceTypeDto(self):
        """Test PriceTypeDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = avacloud_client_python.models.price_type_dto.PriceTypeDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()

