# coding: utf-8

"""
    AVACloud API 1.5.3

    AVACloud API specification  # noqa: E501

    OpenAPI spec version: 1.5.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import avacloud_client_python
from avacloud_client_python.models.destination_gaeb_type import DestinationGaebType  # noqa: E501
from avacloud_client_python.rest import ApiException


class TestDestinationGaebType(unittest.TestCase):
    """DestinationGaebType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDestinationGaebType(self):
        """Test DestinationGaebType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = avacloud_client_python.models.destination_gaeb_type.DestinationGaebType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
