# coding: utf-8

"""
    AVACloud API 1.9.1

    AVACloud API specification  # noqa: E501

    OpenAPI spec version: 1.9.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import avacloud_client_python
from avacloud_client_python.models.forgot_password_post import ForgotPasswordPost  # noqa: E501
from avacloud_client_python.rest import ApiException


class TestForgotPasswordPost(unittest.TestCase):
    """ForgotPasswordPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testForgotPasswordPost(self):
        """Test ForgotPasswordPost"""
        # FIXME: construct object with mandatory attributes with example values
        # model = avacloud_client_python.models.forgot_password_post.ForgotPasswordPost()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
