# coding: utf-8

"""
    AVACloud API 1.9.1

    AVACloud API specification  # noqa: E501

    OpenAPI spec version: 1.9.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import avacloud_client_python
from avacloud_client_python.models.catalogue_type_dto import CatalogueTypeDto  # noqa: E501
from avacloud_client_python.rest import ApiException


class TestCatalogueTypeDto(unittest.TestCase):
    """CatalogueTypeDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCatalogueTypeDto(self):
        """Test CatalogueTypeDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = avacloud_client_python.models.catalogue_type_dto.CatalogueTypeDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
