# coding: utf-8

"""
    AVACloud API 1.52.1

    AVACloud API specification  # noqa: E501

    OpenAPI spec version: 1.52.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""




import unittest

import avacloud_client_python
from avacloud_client_python.api.ugl_conversion_api import UglConversionApi  # noqa: E501
from avacloud_client_python.rest import ApiException


class TestUglConversionApi(unittest.TestCase):
    """UglConversionApi unit test stubs"""

    def setUp(self):
        self.api = avacloud_client_python.api.ugl_conversion_api.UglConversionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_ugl_conversion_convert_to_ava(self):
        """Test case for ugl_conversion_convert_to_ava

        Converts Ugl files to Dangl.AVA projects  # noqa: E501
        """
        pass

    def test_ugl_conversion_convert_to_flat_ava(self):
        """Test case for ugl_conversion_convert_to_flat_ava

        Converts Ugl files to Dangl.AVA projects  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
