# coding: utf-8

"""
    AVACloud API 1.41.0

    AVACloud API specification  # noqa: E501

    OpenAPI spec version: 1.41.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""




import unittest

import avacloud_client_python
from avacloud_client_python.models.token_refresh_post import TokenRefreshPost  # noqa: E501
from avacloud_client_python.rest import ApiException


class TestTokenRefreshPost(unittest.TestCase):
    """TokenRefreshPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTokenRefreshPost(self):
        """Test TokenRefreshPost"""
        # FIXME: construct object with mandatory attributes with example values
        # model = avacloud_client_python.models.token_refresh_post.TokenRefreshPost()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()

