# coding: utf-8

"""
    AVACloud API 1.52.1

    AVACloud API specification  # noqa: E501

    OpenAPI spec version: 1.52.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import avacloud_client_python
from avacloud_client_python.api.x_rechnung_conversion_api import XRechnungConversionApi  # noqa: E501
from avacloud_client_python.rest import ApiException


class TestXRechnungConversionApi(unittest.TestCase):
    """XRechnungConversionApi unit test stubs"""

    def setUp(self):
        self.api = avacloud_client_python.api.x_rechnung_conversion_api.XRechnungConversionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_x_rechnung_conversion_convert_ava_to_x_rechnung(self):
        """Test case for x_rechnung_conversion_convert_ava_to_x_rechnung

        This will convert an AVA wrapper object to an XRechnung file  # noqa: E501
        """
        pass

    def test_x_rechnung_conversion_convert_invoice_to_x_rechnung(self):
        """Test case for x_rechnung_conversion_convert_invoice_to_x_rechnung

        This will convert an Invoice object to an XRechnung file  # noqa: E501
        """
        pass

    def test_x_rechnung_conversion_convert_x_rechnung_to_ava(self):
        """Test case for x_rechnung_conversion_convert_x_rechnung_to_ava

        This will read an XRechnung file and convert it to an AVA wrapper object  # noqa: E501
        """
        pass

    def test_x_rechnung_conversion_convert_x_rechnung_to_invoice(self):
        """Test case for x_rechnung_conversion_convert_x_rechnung_to_invoice

        This will read an XRechnung file and convert it to an Invoice object  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
