# coding: utf-8

"""
    AVACloud API 1.17.0

    AVACloud API specification  # noqa: E501

    OpenAPI spec version: 1.17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import avacloud_client_python
from avacloud_client_python.models.complemented_by_quantity_dto import ComplementedByQuantityDto  # noqa: E501
from avacloud_client_python.rest import ApiException


class TestComplementedByQuantityDto(unittest.TestCase):
    """ComplementedByQuantityDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComplementedByQuantityDto(self):
        """Test ComplementedByQuantityDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = avacloud_client_python.models.complemented_by_quantity_dto.ComplementedByQuantityDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
