# coding: utf-8

"""
    AVACloud API 1.7.5

    AVACloud API specification  # noqa: E501

    OpenAPI spec version: 1.7.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import avacloud_client_python
from avacloud_client_python.models.token_response_get import TokenResponseGet  # noqa: E501
from avacloud_client_python.rest import ApiException


class TestTokenResponseGet(unittest.TestCase):
    """TokenResponseGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTokenResponseGet(self):
        """Test TokenResponseGet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = avacloud_client_python.models.token_response_get.TokenResponseGet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
