# coding: utf-8

"""
    AVACloud API 1.10.0

    AVACloud API specification  # noqa: E501

    OpenAPI spec version: 1.10.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import avacloud_client_python
from avacloud_client_python.models.token_login_post import TokenLoginPost  # noqa: E501
from avacloud_client_python.rest import ApiException


class TestTokenLoginPost(unittest.TestCase):
    """TokenLoginPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTokenLoginPost(self):
        """Test TokenLoginPost"""
        # FIXME: construct object with mandatory attributes with example values
        # model = avacloud_client_python.models.token_login_post.TokenLoginPost()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
